# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/nbdev2-trial',
                'doc_host': 'https://Rushil-Gupta.github.io',
                'git_url': 'https://github.com/Rushil-Gupta/nbdev2-trial',
                'lib_path': 'nbdev2_trial'},
  'syms': {'nbdev2_trial.core': {'nbdev2_trial.core.foo': ('core.html#foo', 'nbdev2_trial/core.py')}}}