# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/nbdev2-trial',
                'doc_host': 'https://Rushil-Gupta.github.io',
                'git_url': 'https://github.com/Rushil-Gupta/nbdev2-trial',
                'lib_path': 'nbdev2_trial'},
  'syms': { 'nbdev2_trial.card': { 'nbdev2_trial.card.Card': ('card.html#card', 'nbdev2_trial/card.py'),
                                   'nbdev2_trial.card.Card.__eq__': ('card.html#card.__eq__', 'nbdev2_trial/card.py'),
                                   'nbdev2_trial.card.Card.__gt__': ('card.html#card.__gt__', 'nbdev2_trial/card.py'),
                                   'nbdev2_trial.card.Card.__init__': ('card.html#card.__init__', 'nbdev2_trial/card.py'),
                                   'nbdev2_trial.card.Card.__lt__': ('card.html#card.__lt__', 'nbdev2_trial/card.py'),
                                   'nbdev2_trial.card.Card.__str__': ('card.html#card.__str__', 'nbdev2_trial/card.py')},
            'nbdev2_trial.deck': { 'nbdev2_trial.deck.Deck': ('deck.html#deck', 'nbdev2_trial/deck.py'),
                                   'nbdev2_trial.deck.Deck.__contains__': ('deck.html#deck.__contains__', 'nbdev2_trial/deck.py'),
                                   'nbdev2_trial.deck.Deck.__init__': ('deck.html#deck.__init__', 'nbdev2_trial/deck.py'),
                                   'nbdev2_trial.deck.Deck.__len__': ('deck.html#deck.__len__', 'nbdev2_trial/deck.py'),
                                   'nbdev2_trial.deck.Deck.__str__': ('deck.html#deck.__str__', 'nbdev2_trial/deck.py'),
                                   'nbdev2_trial.deck.Deck.pop': ('deck.html#deck.pop', 'nbdev2_trial/deck.py')}}}